version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: user-service-mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'userservice'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
